# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 04:40
from __future__ import unicode_literals

import book.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=10)),
                ('origin_price', models.DecimalField(decimal_places=2, max_digits=2, max_length=6, validators=[book.validators.validate_not_negative_number])),
                ('stock', models.IntegerField(validators=[book.validators.validate_not_negative_number])),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=2, max_length=3, validators=[book.validators.validate_discount])),
                ('sale_number', models.IntegerField(default=0, validators=[book.validators.validate_not_negative_number])),
                ('is_on_sale', models.BooleanField(default=True)),
                ('putaway_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='img/cover/default.jpg', null=True, upload_to='img/cover')),
                ('catalogue', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=1000, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
    ]
