# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 15:13
from __future__ import unicode_literals

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, validators=[book.validators.validate_not_negative_number]),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='catalogue',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='summary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
