# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 03:34
from __future__ import unicode_literals

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180509_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='catalogue',
            field=models.FileField(null=True, upload_to=book.models.get_book_file_path),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='cover',
            field=models.ImageField(default='img/cover/default.jpg', null=True, upload_to=book.models.get_book_file_path),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='summary',
            field=models.FileField(null=True, upload_to=book.models.get_book_file_path),
        ),
    ]
