# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 04:16
from __future__ import unicode_literals

import book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180512_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='origin_price',
            field=models.FloatField(max_length=6, validators=[book.validators.validate_not_negative_number]),
        ),
    ]
