# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180512_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='putaway_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
