# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_book_bookdetail'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=16, null=True, validators=[user.validators.validate_phone])),
                ('shopping_cart', models.ManyToManyField(related_name='shopping_cart', to='book.Book')),
                ('trove_books', models.ManyToManyField(related_name='trove_books', to='book.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveInformation',
            fields=[
                ('receive_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_province', models.CharField(default='暂无省份', max_length=10, null=True)),
                ('address_city', models.CharField(default='暂无城市', max_length=10, null=True)),
                ('address_town', models.CharField(default='暂无城区', max_length=10, null=True)),
                ('address_detailed', models.CharField(default='暂无详细地址', max_length=40)),
                ('phone', models.CharField(max_length=16, validators=[user.validators.validate_phone])),
                ('recipient', models.CharField(default='暂无收件人', max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
