# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import order.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_count', models.IntegerField(default=0, validators=[order.validators.validate_not_negative_number])),
                ('price', models.DecimalField(decimal_places=2, max_digits=2, max_length=6, validators=[order.validators.validate_not_negative_number])),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=2, max_length=6, validators=[order.validators.validate_not_negative_number])),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=2, max_length=8, validators=[order.validators.validate_not_negative_number])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
