# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import order.validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book_count',
            new_name='sale_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, max_length=6, validators=[order.validators.validate_not_negative_number]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_fees',
            field=models.FloatField(default=0, max_length=8, validators=[order.validators.validate_not_negative_number]),
        ),
    ]
