# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import order.validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180513_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1, validators=[order.validators.validate_order_status]),
        ),
    ]
